trigger:
- main
- test-snapshot-feed

pool:
  vmImage: ubuntu-22.04

steps:
- bash: |
    echo "user: $ADO_USERNAME"
    echo "pwd: $ADO_PASSWORD"
  env:
    ADO_USERNAME: $(ADO_USERNAME)
    ADO_PASSWORD: $(ADO_PASSWORD) # secret variable has to be mapped to an env variable

- bash: |
    echo "gpg version:"
    gpg --version
    echo "GPG_TTY: $GPG_TTY"
    echo "running agent:"
    ps ax | grep gpg
    echo "list keys:"
    gpg --list-keys
    echo "importing key:"
    # Pipeline variables do not preserve line ends so we use base64 as a workaround.
    echo $GPG_PRIVATE_KEY_BASE64 | base64 -d | gpg --batch --import
    echo "list keys after import:"
    gpg --list-keys
    echo "running agent after import:"
    ps ax | grep gpg
  env:
   GPG_PRIVATE_KEY_BASE64: $(GPG_PRIVATE_KEY_BASE64) # secret variable has to be mapped to an env variable
  displayName: "Import gpg key"

- bash: ./scripts/download_driver_for_all_platforms.sh

- bash: mvn -B deploy -D skipTests --no-transfer-progress --activate-profiles release --settings maven-settings.xml -D gpg.passphrase=$GPG_PASSPHRASE
  displayName: 'Deploy'
  env:
    ADO_USERNAME: $(ADO_USERNAME)
    ADO_PASSWORD: $(ADO_PASSWORD) # secret variable has to be mapped to an env variable
    GPG_PASSPHRASE: $(GPG_PASSPHRASE) # secret variable has to be mapped to an env variable
