trigger:
- main
- test-snapshot-feed

pool:
  vmImage: ubuntu-22.04

steps:
- script: bash ./scripts/download_driver_for_all_platforms.sh

- script: mvn -B deploy -D skipTests --no-transfer-progress
  displayName: 'Deploy'
  env:
    MAVEN_USERNAME: $(ADO_USERNAME)
    MAVEN_PASSWORD: $(ADO_PASSWORD)
