trigger:
- main
- test-snapshot-feed

pool:
  vmImage: ubuntu-22.04

steps:
- script: echo "username = '$MAVEN_USERNAME'"
  displayName: 'Echo username'
  env:
    MAVEN_USERNAME: $(ADO_USERNAME)
    MAVEN_PASSWORD: $(ADO_PASSWORD)

