trigger:
- main
- test-snapshot-feed

pool:
  vmImage: ubuntu-22.04

steps:
- script: echo "username = $ADO_USERNAME "
  displayName: 'Echo username'

- script: echo "password = $ADO_PASSWORD"
  displayName: 'Echo passwd '
  env:
    ADO_USERNAME: $(ADO_USERNAME)
    ADO_PASSWORD: $(ADO_PASSWORD)

- bash: echo "PASSWORD = $PASSWORD"
  displayName: 'Echo passwd '
  env:
    PASSWORD: $(ADO_PASSWORD)

- bash: echo "PPP = $PPP"
  displayName: 'Echo ppp '
  env:
    PPP: $(MY_SECRET)

- bash: echo "PPP2 = $PPP"
  displayName: 'Echo ppp2 '
  env:
    PPP: $MY_SECRET

- bash: |
    echo "Using the mapped env var for this task works and is recommended: $MY_MAPPED_ENV_VAR"
  env:
    MY_MAPPED_ENV_VAR: $(MY_SECRET) # the recommended way to map to an env variable


- script: bash ./scripts/download_driver_for_all_platforms.sh

- script: mvn -B deploy -D skipTests --no-transfer-progress --settings maven-settings.xml
  displayName: 'Deploy'
  env:
    ADO_USERNAME: $(ADO_USERNAME)
    ADO_PASSWORD: $(ADO_PASSWORD)
